version: "3.8"

services:
  postgres:
    container_name: NIRSpostgres
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASS}
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40
    env_file:
      - .env

  pgadmin:
    container_name: NIRSpgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL={PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD={PGADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    env_file:
      - .env
